### ISSUE TITLE
how to use spec augment ?

### ISSUE THREAD

**Issue by amine-boukriba** [iver56/audiomentations#100]
hi guys I am new to python and audiomentations and I want to use all the available spectrogram augmentations possible and I didn't know how to use this library and didn't find any code example. if you used these features before please share your code.
cheers

**Comment by iver56** [comment]
Hi :) Sorry for the lack of example. Perhaps the tests could help you for the time being?

* https://github.com/iver56/audiomentations/blob/master/tests/test_spec_frequency_mask.py
* https://github.com/iver56/audiomentations/blob/master/tests/test_spec_channel_shuffle.py
* https://github.com/iver56/audiomentations/blob/master/tests/test_spec_compose.py

**Comment by atamazian** [comment]
This is not really an issue, I believe it should be closed.

**Comment by iver56** [comment]
I've added an example in readme: https://github.com/iver56/audiomentations#spectrogram
