### ISSUE TITLE
Why output many \n? 

### ISSUE THREAD

**Issue by shawnthu** [iver56/audiomentations#109]
Anyone encounter such case?

**Comment by iver56** [comment]
Could you please elaborate?

**Comment by shawnthu** [comment]
> Could you please elaborate?

![image](https://user-images.githubusercontent.com/11691764/122009811-0a60ee80-cded-11eb-9f6e-8761a3b6d575.png)

This is my augmentation configure file. When I use it to augment each audio sample for a audio-related dnn training task, it outpus many \n character, namely empty row to my log file.

**Comment by iver56** [comment]
Does this augmentation configuration file relate to some glue code you have written yourself?

I cannot at the moment explain why you are seeing lots of newline characters in your log file

**Comment by iver56** [comment]
If I were you, I would search for things like "print(" and "logging." in the code. Also check third-party programs that are called via subprocess.

**Comment by shawnthu** [comment]
> If I were you, I would search for things like "print(" and "logging." in the code. Also check third-party programs that are called via subprocess.

Found it!

When I call as follows
![image](https://user-images.githubusercontent.com/11691764/122052979-e3201680-ce18-11eb-845e-a049107fb722.png)

and augment in fact is "Compose"
![image](https://user-images.githubusercontent.com/11691764/122053014-ef0bd880-ce18-11eb-8013-dbde492ba46e.png)

To my surprise, 
    1. I don't know which cause the exception
    2. why the exception outputs nothing?

**Comment by atamazian** [comment]
This doesn't look related to `audiomentation` package itself. I suggest to close this issue.

**Comment by iver56** [comment]
@shawnthu Can you try to step-debug to figure out what the exception is?

**Comment by shawnthu** [comment]
> @shawnthu Can you try to step-debug to figure out what the exception is?

I guess it is caused by Mp3 augmentation. After comment it, the procedure works normally.

**Comment by iver56** [comment]
Have you tried to switch the `backend` of `Mp3Compression` from `pydub` to `lameenc`? Have you checked that ffmpeg is correctly installed?

Which version of pydub do you have? In the release notes of pydub 0.24.1 it says "Fix bug where ffmpeg errors in Python 3 are illegible"

https://github.com/jiaaro/pydub/releases

**Comment by shawnthu** [comment]
![image](https://user-images.githubusercontent.com/11691764/122424095-05ed2f00-cfc1-11eb-968f-da3ca0e059e0.png)

Got it! After previous 'AddBackgroundNoise' augmentation, the output seems dtype float64.

**Comment by shawnthu** [comment]
I see it has been fixed in the newest commit. 
issue can be closed. thx a lot!

**Comment by iver56** [comment]
So the real bug is that the AddBackgroundNoise transform was outputting float64? Does the dev version (currently master) correctly output float32?

**Comment by shawnthu** [comment]
> So the real bug is that the AddBackgroundNoise transform was outputting float64? Does the dev version (currently master) correctly output float32?

Sorry for reply so late. I made mistakes before. BTW, pleast revert my pr.

**Comment by iver56** [comment]
Ok, no worries
