### ISSUE TITLE
Need to know the significance of min and max amplitude of Gaussian noise and min & max rate of Time Stretch

### ISSUE THREAD

**Issue by arakis92** [iver56/audiomentations#116]
Why the values are mentioned like that ?
AddGaussianNoise(min_amplitude=0.001, max_amplitude=0.015, p=0.5),
TimeStretch(min_rate=0.8, max_rate=1.25, p=0.5),

Is it by default? 

If my signal's sample rate is 8K and min & max amplitude are within the range of -0.03 to 0.03, what should be the values of the parameters?

**Comment by iver56** [comment]
min_amplitude and max_ampliude are expected to be positive. Every time AddGaussianNoise adds nose, it will pick a random amplitude between the given min and max amplitude, and use that as a factor for the noise. Greater amplitude means more noise.

If I were you, I would play with the numbers and listen to the results - the ear is a useful organ :)

**Comment by iver56** [comment]
If your input audio is not very loud (e.g. if all your samples lie between -0.03 and 0.03), you could try to lower the noise that you add. It depends on the application.
