### ISSUE TITLE
Add equalizer transformation

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#12]

**Comment by atamazian** [comment]
Can you provide additional info?

**Comment by iver56** [comment]
Sure! Here is an example screenshot of an equalizer plugin in FL Studio:

![bilde](https://user-images.githubusercontent.com/1470603/125909437-7a5ceaf0-da35-4639-9fc0-1657f97b6f1f.png)

This plugin shows 7 different bands. It changes the spectrum of the sound according to the dips and boost that the user can set. Note that band 1type  is "low shelf" while the band 7 type is "high shelf". The 5 bands in the middle have the "peaking" type.

Each band has a number of parameters: Frequency, bandwidth, gain in dB (can be both positive and negative) and order (all the way from gentle to steep).

Now imagine a data augmentation transform that applies a number of bands (like the plugin shown above) and randomizes some parameters so that the spectrum of the audio changes in a random way.

Note that the recently released AugLy has a transform called PeakingEqualizer, which is a single-band equalizer. I guess by combining a number of those, we can get a more comprehensive equalizer, like the plugin shown in the screenshot above.

https://github.com/facebookresearch/AugLy/blob/d18d7bcb4bcc990ff6377d96c4fbe38fa764c7e9/augly/audio/transforms.py#L550
