### ISSUE TITLE
0.18.0 release?

### ISSUE THREAD

**Issue by turian** [iver56/audiomentations#125]
When will 0.18.0 be released? We are excited to use it.

**Comment by iver56** [comment]
I'm not sure yet, but you can start trying it already if you want :) I think you can do this to install the latest master branch of audiomentations:

`pip install git+https://github.com/iver56/audiomentations`

This is my list of things to fix before releasing 0.18.0:

* Make sure the added distortion of TanhDistortion depends less on the loudness of the input. Pick uniform gain in db, not amplitude ratio? not sure about this.
* fix the failing tanhdistortion tests
* listen to the tanhdistortion results

**Comment by iver56** [comment]
Hmm, I could postpone TanhDistortion to 0.19.0. That would speed up the 0.18.0 release.

**Comment by iver56** [comment]
0.18.0 has been released
