### ISSUE TITLE
Example background noise folder?

### ISSUE THREAD

**Issue by turian** [iver56/audiomentations#126]
Could you provide a link to an example folder of background noise?

This is provided for impulse response and would also be great for noise.

**Comment by iver56** [comment]
Hi turian :)
If you're into animal sounds in ogg vorbis format, perhaps this folder can serve as example folder of background noise? https://github.com/iver56/audiomentations/tree/master/demo/background_noises

**Comment by iver56** [comment]
Oh, wait, I think you meant something more comprehensive, beyond just a technical "does it work" check. In that case, there are many options*, and they are going to depend on sample rate, how large a dataset you want, the license, etc. Maybe it's best to link to an "awesome background noise datasets" github page or something?

*The first one that comes to mind DNS challenge, which contains audio recordings from AudioSet and Freesound:
https://github.com/microsoft/DNS-Challenge/tree/master/datasets

**Comment by turian** [comment]
Yes, a link to a comprehensive dataset would be great!

**Comment by atamazian** [comment]
I think this issue is solved and should be closed.
