### ISSUE TITLE
Why not use T60 as the parameter of  ApplyImpulseResponse? 

### ISSUE THREAD

**Issue by Ryuk17** [iver56/audiomentations#128]
It will be easizer to use.

**Comment by iver56** [comment]
Hi Ryuk17. Thanks for your suggestion. That would be a good parameter for a reverb transform. However, `ApplyImpulseResponse` is not purely for reverb. It could be used for various filters (HPF, LPF, BPF), delay, echo and other things - it is quite flexible and user-defined (by the wavs it should use as kernels). Note also that two reverbs with the same T60 can sound very different. But yeah, I can see that it would be nice to have an easy to use reverb transform without the need for downloading and keeping a RIR dataset.

Audiomentations could have both `ApplyImpulseResponse` and an `AddReverb` transform.

**Comment by Ryuk17** [comment]
> This seems a nice use case for #165

That's cool.
