### ISSUE TITLE
Change default value of leave_length_unchanged to True

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#161]
But deprecate "not specifying a value" first.

Motivation: the default would cut off the sound to digital silence and then have a tail of only reverb, and it doesn't sound so natural. Maybe except for music applications.

**Comment by iver56** [comment]
https://github.com/iver56/audiomentations/commit/3f319821afe5034e45f0236ccc1d007908488605

**Comment by atamazian** [comment]
This issue seems to be solved, so can you close it?
