### ISSUE TITLE
Move changelog from README.md to CHANGELOG.md

### ISSUE THREAD

**Issue by atamazian** [iver56/audiomentations#166]
I suggest to move changelog from README.md to CHANGELOG.md since changelog became quite large.

**Comment by mmxgn** [comment]
I agree with @atamazian. Alternatively, to not lose content in README.md we can use:

<details><summary> collapsible markdown: </summary>


https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f
</details>

**Comment by iver56** [comment]
I kind of want to make a website for audiomentations one day™️

The changelog could be its own page
