### ISSUE TITLE
Clarification: Does the parameter p hold any relevance when there is only one transform to apply?

### ISSUE THREAD

**Issue by PrabhjotKaurGosal** [iver56/audiomentations#168]
Hello,

Firstly, thanks to the team for making this library available.
I wanted to clarify if my understanding of the parameter 'p' when applying audio transformations is correct. I found the following in one of the files.
"param p: The probability of applying this transform".

So, does this mean that if I am applying only one transformation at a time such as AddGaussianNoise, then setting value for p is irrelevant?
sample_GaussianNoise = Compose([AddGaussianNoise(min_amplitude=0.001, max_amplitude=0.015, p=0.5)])

My understanding of this parameter is that when we have more than one transformations specified in Compose, and we want to apply only handful of them at a time, then p is the probability that a given transform will be applied to the audio? Is this the correct understanding?

Thanks!

**Comment by iver56** [comment]
> Firstly, thanks to the team for making this library available.

Thanks for the appreciation

> p is the probability that a given transform will be applied to the audio

Yes.

p=0.0 (noop)
p=0.5 (randomly apply 50% of the times it gets called)
p=1.0 (apply every time it gets called)

This parameter was inspired by [albumentations](https://github.com/albumentations-team/albumentations)

Whether or not this parameter is relevant is up to you and your use case
