### ISSUE TITLE
Improve consistency: min_gain_db vs. min_gain_in_db

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#177]
Do we want to align parameter names like that? If we choose one of them, which one is better? min_gain_db or min_gain_in_db?

**Comment by mmxgn** [comment]
I would be in favour of `min_gain_db` since it provides exactly the information needed (minimum, a gain value, in db unit).

**Comment by iver56** [comment]
The guys in asteroid slack agree with you unanimously (7 votes received)

**Comment by atamazian** [comment]
I also think that `min_gain_db` is a better option.

**Comment by atamazian** [comment]
It seems that most people voted for the `min_gain_db` option. I suggest to close this issue.

**Comment by iver56** [comment]
TODO:

- [ ] start using `min_gain_db` instead of `min_gain_in_db` in `Gain` and `GainTransition`. It should be done in a backwards-compatible manner.
