### ISSUE TITLE
Use FutureWarning instead of generic warning

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#184]
Related to

https://github.com/iver56/audiomentations/issues/179
https://github.com/iver56/audiomentations/issues/177
https://github.com/iver56/audiomentations/issues/173
https://github.com/iver56/audiomentations/issues/172
https://github.com/iver56/audiomentations/issues/161

**Comment by atamazian** [comment]
I think this issue is solved, so it should be closed.
