### ISSUE TITLE
Error: ValueError: empty range for randrange() (0,-47799, -47799)

### ISSUE THREAD

**Issue by PrabhjotKaurGosal** [iver56/audiomentations#185]
Hello,
I am getting the error for some of the augmentations. 
ValueError: empty range for randrange() (0,-47799, -47799)

For example, I define TimeMask augmentation as follows. I get the above error when I apply this to an audio, with sample_rate=16000. I am not sure what could be causing this error.
TimeMask_2 = Compose([TimeMask(min_band_part=0.5, max_band_part=1.5, fade=True, p=1.0)])

Any suggestions would be helpful. Thanks!

**Comment by iver56** [comment]
Heyo. Can you try to adjust your max_band_part? 1.5 seems like an invalid value, and I think the maximum supported value is 1.0, or just below that. 1.0 would mean that the entire audio gets silenced. Perhaps the class should do some sanity checks of the given values...

**Comment by iver56** [comment]
I've added a guard:

https://github.com/iver56/audiomentations/commit/53e7984c3f37674ee88f02e426fe0a63b587f8fe

It will make a gesture somewhat like this every time you give it a max_band_part that is greater than 1.0:

![le guard](https://media.giphy.com/media/l0HUfgeRdp38flYmQ/giphy.gif)

**Comment by PrabhjotKaurGosal** [comment]
Thank you so much for the quick response!
"max_band_part" being greater than 1 was exactly the reason for the error I was getting.
