### ISSUE TITLE
Document all available transforms

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#19]

**Comment by iver56** [comment]
Gotta start somewhere 🤷 https://github.com/iver56/audiomentations/commit/35b952fb2755b1b348f5f76809fb99448ae59019

**Comment by iver56** [comment]
https://quarto.org/ looks compelling. It can be deployed on Github Pages, like https://github.com/drscotthawley/aeiou/blob/main/.github/workflows/deploy.yaml

**Comment by iver56** [comment]
Good old sphinx is probably a better alternative

**Comment by iver56** [comment]
I went with mkdocs for now. It's simple, it feels like smooth sailing, and I like early results already

**Comment by iver56** [comment]
Not sure how to do the API documentation. Here are some styles:

# 1

![bilde](https://user-images.githubusercontent.com/1470603/189363980-4dd8a117-717c-4a51-8e1b-b690b90fd3ee.png)

# 2

![bilde](https://user-images.githubusercontent.com/1470603/189364023-f3240f73-311e-4563-b90d-9d525fd30a0d.png)

# 3

![bilde](https://user-images.githubusercontent.com/1470603/189364146-987dc33a-d360-43ef-bb71-ab21202ba49f.png)

I think I'm leaning towards 1, because the markdown for it is more maintainable and it looks a bit prettier

**Comment by Thanatoz-1** [comment]
Hi @iver56, 
I would like to help with this issue.
Is there anything specific, I should be taking care of, apart from everything mentioned in this and other issues?

**Comment by iver56** [comment]
Hi @Thanatoz-1

Help is appreciated :) As you can see from the commits lately, I have begun working on the documentation already, but most of the waveform transforms docs are still incomplete. If you could start from the bottom alphanumerically (so Trim, TimeStretch, etc), I can keep working my way from the top, so we don't do the same work.

The documentation website is currently based on mkdocs-material. To get started with that locally, you need to install the dependencies here: https://github.com/iver56/audiomentations/blob/master/docs/requirements.txt

Then you can run `mkdocs serve` (from the root folder of the project, I think, not docs) and open localhost:8000 in your browser.

I want to ideally have all the following things for each waveform transform:

* class name (the header)
* description
* input-output example (visualization and audio)
* usage example (one or more)
* API

I have a few transforms that contain all those things already, so you can look at those for inspiration;

* https://github.com/iver56/audiomentations/blob/master/docs/waveform_transforms/add_background_noise.md
* https://github.com/iver56/audiomentations/blob/master/docs/waveform_transforms/add_gaussian_noise.md

Input-output examples (image and audio) can be created by adding code here and then running the script:

https://github.com/iver56/audiomentations/blob/master/demo/generate_examples_for_doc.py#L98
