### ISSUE TITLE
Bug in RoomSimulator execution

### ISSUE THREAD

**Issue by skol101** [iver56/audiomentations#201]
Code
```python
augmenter = Compose(
                [
                    RoomSimulator(
                        p=1.0,
                        leave_length_unchanged=True,
                    ),
                    AddBackgroundNoise(
                        sounds_path=os.path.join(random.choice(BACKGROUND_NOISE_FILES)),
                        min_snr_in_db=15,
                        max_snr_in_db=35,
                        p=1.0,
                    )
                ]
            )
            wave = augmenter(samples=wave, sample_rate=sample_rate)
```

Trace:
```
 File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/audiomentations/core/composition.py", line 88, in __call__
    samples = transform(samples, sample_rate)
  File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/audiomentations/core/transforms_interface.py", line 62, in __call__
    self.randomize_parameters(samples, sample_rate)
  File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/audiomentations/augmentations/room_simulator.py", line 339, in randomize_parameters
    self.room.compute_rir()
  File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/pyroomacoustics/room.py", line 2156, in compute_rir
    vis = self.visibility[s][m, :].astype(np.int32)
IndexError: list index out of range

```

It happens occasionally on specific wav files.

**Comment by mmxgn** [comment]
Hi,

Could you also take a look at the error message you posted? The exception type is missing. 

It would be helpful if you attached a .wav file that causes the issue so we can reproduce it.

**Comment by skol101** [comment]
[roomsimulator-example-wave.zip](https://github.com/iver56/audiomentations/files/8863472/roomsimulator-example-wave.zip)
Here's an example . Updated topic post with error.

**Comment by skol101** [comment]
Another error 
```
 File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/audiomentations/augmentations/room_simulator.py", line 311, in randomize_parameters
    self.room.add_source(
  File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/pyroomacoustics/room.py", line 1955, in add_source
    return self.add(SoundSource(position, signal=signal, delay=delay))
  File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/pyroomacoustics/room.py", line 1808, in add
    raise ValueError("The source must be added inside the room.")
ValueError: The source must be added inside the room
```

**Comment by mmxgn** [comment]
Thank you for your reply. I will try to reproduce the error today.

Can you give us the snippet that produced "Another Error"?

**Comment by atamazian** [comment]
@iver56 Can you add "bug" label to this issue?

**Comment by skol101** [comment]
> Thank you for your reply. I will try to reproduce the error today.
> 
> Can you give us the snippet that produced "Another Error"?

It's the same code.

**Comment by skol101** [comment]
At first I thought the issue was with pyroomacoustics, so I pulled latest commit from their repo. But that didn't help.

**Comment by mmxgn** [comment]
Can you post a minimal python script using that file that causes your errors? Including how you load the file and how you pass `sample_rate`.

I tried with:

```python
from audiomentations import Compose, RoomSimulator
import librosa

wave, sr = librosa.core.load("16.wav", mono=False)

augmenter = Compose(
    [
        RoomSimulator(
            p=1.0,
            leave_length_unchanged=True,
        ),
    ]
)

wave = augmenter(samples=wave, sample_rate=sr)
```

But cannot get the exception.

**Comment by mmxgn** [comment]
Seems like when `padding` is `0.1` in this case, `self.room.compute_rir()` causes the first error (`mic_x` gets very close to the edge). I'd need to look closer into pyroomacoustics to see what's going on. I'd suggest increasing the padding to 0.15 for now.

**Comment by azinonos** [comment]
Commenting on this as I'm experiencing the same error "ValueError: The source must be added inside the room", even after the above fix. It's happening within a PyTorch Dataloader.

**Comment by iver56** [comment]
> Commenting on this as I'm experiencing the same error "ValueError: The source must be added inside the room", even after the above fix. It's happening within a PyTorch Dataloader.

Can you create a new issue with a few more details? Like a small code snippet for reproduction and the version of audiomentations you used
