### ISSUE TITLE
CircleCI obsolete Docker image

### ISSUE THREAD

**Issue by atamazian** [iver56/audiomentations#203]
When I run CircleCI check on my forked repo, I've got this message:

"You’re using a [deprecated Docker convenience image.](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) Upgrade to a next-gen Docker convenience image."

Does this need to be fixed by changing `.circleci/config.yml`, or it can be left as it is for now?

**Comment by iver56** [comment]
Hmm, I haven't seen that before. Maybe the fix is to do something like this?

https://circleci.com/docs/2.0/next-gen-migration-guide/

If you figure it out, please share

**Comment by atamazian** [comment]
I fixed this, but I had to change cache version to v2 in order to update it. Also I removed `ppa:jonathonf/ffmpeg-4` repo from `config.yml` since it's obsolete and not necessary. You can check CircleCI log from here https://github.com/iver56/audiomentations/pull/200

**Comment by iver56** [comment]
Thanks for sharing :) I'll see if I can update it

**Comment by atamazian** [comment]
Also you are using very old codecov - 1.0.4. On their website they suggest to use 3.2.3 - https://circleci.com/developer/orbs/orb/codecov/codecov

**Comment by iver56** [comment]
It has been updated

https://github.com/iver56/audiomentations/commits/master/.circleci/config.yml
