### ISSUE TITLE
Problem with Python 3.9

### ISSUE THREAD

**Issue by atamazian** [iver56/audiomentations#208]
I noticed that you switched to Python 3.9 in CircleCI config; however, this caused a problem since `lameenc==1.2.2` is not available for this version of Python. I suggest to change Python version back to 3.8.12, or change used `lameenc` version.

**Comment by iver56** [comment]
I upgraded lameenc in 6e0969d65c9a280b7e8cc0f7fa28f3327d128e89 already. Does it work for you?

**Comment by atamazian** [comment]
You're right, I missed that changes. Everything is working.
