### ISSUE TITLE
any plan to accelerate mp3 degradation, such as c++ implementation?

### ISSUE THREAD

**Issue by huangxu1991** [iver56/audiomentations#220]
lameenc or pydub is sitll too slow, and slow down the data augmentation process

**Comment by iver56** [comment]
If you know a good alternative, please let me know

**Comment by huangxu1991** [comment]
> If you know a good alternative, please let me know

of course!

**Comment by iver56** [comment]
I just did a crude perf test where I degraded a 1 hour noise sound in Audacity (write to mp3 and then load it into memory again) for comparison. Then I did the same thing with audiomentations. Results:

Audacity: 33.7 s
Audiomentations (pydub): 37.8 s
Audiomentations (lameenc): 34.7 s

Just like Audacity (which is coded in C/C++), audiomentations is using compiled code for MP3 encoding and decoding. However, there is a little overhead related to the I/O (write and read file to/from disk), so I guess that's the main area where performance can be improved. If you know how we can achieve that, please reopen the issue. Other than that, I'm afraid we'll have to live with the fact that MP3 encoding and decoding is currently a bit slow by nature.

By the way, using multiprocessing (multiple workers) when applying data augmentation can speed up your execution.

**Comment by iver56** [comment]
Related: https://minds.wisconsin.edu/handle/1793/45041

**Comment by iver56** [comment]
There's also this one: https://github.com/toots/shine

**Comment by shawnthu** [comment]
cool, thx
