### ISSUE TITLE
Most useful augmentation for speech?

### ISSUE THREAD

**Issue by RK-BAKU** [iver56/audiomentations#242]
Hi guys! 

Kindly suggest the most applicable filters as for ASR training tasks.

Thanks in advance!

**Comment by iver56** [comment]
* Shift
* AddGaussianSNR
* AddBackgroundNoise
* AddShortNoises
* GainTransition
* PolarityInversion
* Padding
* PitchShift
* TimeStretch
* Reverse
* Trim
* LowPassFilter
* Resample
* Mp3Compression
* SevenBandParametricEQ
* HighPassFilter
* ApplyImpulseResponse

**Comment by iver56** [comment]
Also, check out the SpecAugment paper
