### ISSUE TITLE
Feature Request: Aliasing

### ISSUE THREAD

**Issue by mmxgn** [iver56/audiomentations#261]
This is a nice degradation which would help imho in restoration algorithms and is provided in the Audio Degradation Toolbox. E.g. do the following:

1. Naively downsample to a lower sample rate without filtering
2. Upsample normally.

**Comment by iver56** [comment]
Yep, good idea

**Comment by atamazian** [comment]
Can you assign me to this issue?

**Comment by iver56** [comment]
Ah, yes, here we have the issue for the stuff I mentioned in #264 

> Sample rate reduction without low-pass filtering. Also known as sample-and-hold or decimation, but I personally like to think of it as nearest neighbour. This is a terrible form of resampling audio quality wise, but it leads to an interesting kind of output that can be used in music (often electronic music), and it can be used for data augmentation if not overdone
> http://gdsp.hf.ntnu.no/lessons/1/3/

I will assign the issue to you, atamazian 👍 Thanks for contributing

**Comment by iver56** [comment]
TODO:
- [ ] Add documentation page
- [ ] Link to it from readme
