### ISSUE TITLE
Allow to provide `AddShortNoises` with a (list of) file path(s)

### ISSUE THREAD

**Issue by mmxgn** [iver56/audiomentations#262]
Right now it only accepts a directory of audio files, it would be good to also allow for list of audio numpy arrays similar to `ApplyImpulseResponse`

**Comment by atamazian** [comment]
The `ApplyImpulseResponse` function doesn't allow a list of audio numpy arrays to be passed as input argument. Maybe you meant some other function?

**Comment by mmxgn** [comment]
Hm, sorry, I meant list of files :P

**Comment by iver56** [comment]
The current implementation seems to allow a list of files:

```
class AddShortNoises(BaseWaveformTransform):
    (...)
    def __init__(
        self,
        sounds_path: Union[List[Path], List[str], Path, str],
        (...)
    ):
        """
        :param sounds_path: A path or list of paths to audio file(s) and/or folder(s) with
            audio files. Can be str or Path instance(s). The audio files given here are
            supposed to be (short) noises.
```

@mmxgn Can you check if your wish is already fulfilled?

**Comment by mmxgn** [comment]
yes it was
