### ISSUE TITLE
Add BitCrush

### ISSUE THREAD

**Issue by mmxgn** [iver56/audiomentations#264]

**Comment by iver56** [comment]
Yup. That page mainly features two different transforms:

1. Sample rate reduction without low-pass filtering. Also known as sample-and-hold or decimation, but I personally like to think of it as nearest neighbour. This is a terrible form of resampling audio quality wise, but it leads to an interesting kind of output that can be used in music (often electronic music), and it can be used for data augmentation if not overdone
2. Bit depth reduction, which reduces the number of bits that can be used for representing each audio sample. This introduces quantization noise which can mess with dynamic range and harmonics, amongst other things.

I think these two are sufficiently different that they should be different augmentation classes in audiomentations.

Based on the issue title, I think this one mainly refers to 2. Bit depth reduction

Would you like to implement it? A PR would be welcome

**Comment by iver56** [comment]
Here's another nice resource on this topic, from a course I took at NTNU a long time ago: http://gdsp.hf.ntnu.no/lessons/1/4/

**Comment by atamazian** [comment]
Thanks for the info. I'll implement this. Please assign this issue to me.

**Comment by iver56** [comment]
TODO:

- [ ] Add documentation page
- [ ] Link to it from readme
