### ISSUE TITLE
add `__repr__` and `__str__` methods for `Compose` etc

### ISSUE THREAD

**Issue by aaprasad** [iver56/audiomentations#285]
`albumentations` has a nice `__repr__` and `__str__` for their `Compose` class that shows the augmentations being used. Would be nice to have the same thing in Compose instead of the generic `<audiomentations.core.composition.Compose object at 0x15546be0cdf0>`

**Comment by atamazian** [comment]
Can you assign this issue to me?

**Comment by atamazian** [comment]
I can tell that it's definitely not "a good first issue". I've made it work though, will commit soon.
