### ISSUE TITLE
Report specific python minor version

### ISSUE THREAD

**Issue by mmxgn** [iver56/audiomentations#318]
Currently Audiomentations will fail for `Python>3.9.x` due to incompatible version with `lameenc` (at least). It would be nice to add the specific python minor version in the readme or elsewhere.

**Comment by iver56** [comment]
When installing audiomentations as a package, it currently officially supports python 3.8 and greater. This is denoted in setup.py here:
https://github.com/iver56/audiomentations/blob/2befa8f6fa9bab9e3f5a4ce387835a44360c99dc/setup.py#L54

The lameenc dependency is currently set to lameenc>=1.2.0,<2. The newest lameenc version at the time of writing is 1.7.0, and seems to support python versions 3.6-3.12
https://github.com/iver56/audiomentations/blob/2befa8f6fa9bab9e3f5a4ce387835a44360c99dc/setup.py#L48

I see that lameenc is pinned to 1.3.1 in requirements.txt, which is only meant for local audiomentations development right now. I will bump that version to extend the range of supported python versions there 👍

**Comment by iver56** [comment]
43d6aa37
