### ISSUE TITLE
Question about documentation creation

### ISSUE THREAD

**Issue by atamazian** [iver56/audiomentations#330]
I'd like to ask how is the documentation created - manually, or with usage of some tools like `doxygen`?

**Comment by iver56** [comment]
Documentation is made manually in the form of markdown files here:
https://github.com/iver56/audiomentations/tree/main/docs

Waveform transform pages should ideally have an example with waveform & spectrogram before and after, as well as playable audio before and after. Those can be made with the following script:
https://github.com/iver56/audiomentations/blob/main/demo/generate_examples_for_doc.py

Github Actions compiles it to a website, using mkdocs-material, and deploys it on Github Pages

Contributions to the documentation, like adding pages for Bitcrush and Aliasing, are welcome 👍 If you have more question, I'd be happy to answer them
