### ISSUE TITLE
Multichannel Audio Training Randomly Freeze

### ISSUE THREAD

**Issue by yuanhong-sony** [iver56/audiomentations#345]
I encounter randomly training freeze (single gpu) while working with the following lines:

```python
aug = Compose([
            AddGaussianNoise(min_amplitude=0.001, max_amplitude=0.015, p=0.5),
            # Reverse(p=0.5),
            TimeStretch(min_rate=0.8, max_rate=1.25, p=0.5),
            PitchShift(min_semitones=-4, max_semitones=4, p=0.5),
            Shift(p=0.5),
        ])
```

**Comment by iver56** [comment]
I'm afraid I cannot help without more info. What do you mean with freeze? Do you have a minimum reproducible code example? Do you know if the problem lies in audiomentations or somewhere else?

**Comment by yuanhong-sony** [comment]
I've been experiencing random training hangs after implementing data augmentation, but it seems like the issue might be caused by another part of the module.

**Comment by iver56** [comment]
Ok, I will close the issue then
