### ISSUE TITLE
Dependencies conflicts: making a more flexible requirements.txt ?

### ISSUE THREAD

**Issue by ArnoBen** [iver56/audiomentations#367]
Hi, thanks for the great repo.

The current `requirements.txt` has many fixed versions which conflict with other of my packages in my environment.
In order to use it I had to fork it and make them more flexible. This worked right away and all tests passed.

Would it be possible to make them less constraining ? I can open a PR for that if desired.
I also converted it to use poetry with a `pyproject.yaml` instead of the old `setup.py` if a PR is of any interest for you.

Cheers

**Comment by iver56** [comment]
requirements.txt just shows an example of a python environment for development of the audiomentations package itself. This is not the recommended option as list of third-party dependencies when integrating audiomentations in your project. As a user of the audiomentations library, the recommended way ot installing it is `pip install audiomentations` (or with your favorite python package manager, be it poetry, uv or something else). In that case, it will not use frozen/constrained requirements mentioned in requirements.txt, but instead it will use the dependencies listed in setup.py: https://github.com/iver56/audiomentations/blob/main/setup.py#L39

The version ranges of the dependencies specified in setup.py should be wide enough for most developers.

Sure, forking the library, as you have done, is also a viable option. pyproject.toml is indeed a more modern way of specifying the package properties, and it could be of interest to switch to that at some point, although the added value (if any) has not made it a top priority to do that yet.

Happy programming!

**Comment by ArnoBen** [comment]
Huh I didn't know pip only checked setup.py, I though it did look for the `requirements.txt` file. The more you know :)
Thank you for your answer !
