### ISSUE TITLE
Make transformations that apply to spectrograms, not waveforms

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#43]
First, it is wise to design an API. Make a clear distinction between waveform transforms and spectrogram transforms.

* Time mask a la spec augment
* Frequency mask a la spec augment
* Time warp a la spec augment
* Pitch shift
* Time stretch
* Shift (with and without rollover)

**Comment by The0nix** [comment]
+1
This is a crucial feature IMO. There is already Frequency Mask, but right now it is very difficult to tell, what transforms operate on what objects. Furthermore, transforms for creating spectrograms themselves are needed: torchaudio ones can not be fitted into audiomentations's Compose.

**Comment by iver56** [comment]
Thanks for your interest in audiomentations! The current `FrequencyMask` transform applies directly to the waveform, and its filter is not as sharp as it would be in the spectrogram space. If you would like to contribute, you are welcome, and you might even get some Hacktoberfest points for it 😉 

Spectrograms from torchaudio would indeed need to be converted to an appropriately shaped numpy ndarray before they could be used in audiomentations. For a pytorch version of audiomentations, check out this initiative: https://github.com/asteroid-team/torch-audiomentations

**Comment by iver56** [comment]
Some spectrogram transforms are now available in master. See https://github.com/iver56/audiomentations/pull/60

Thoughts?

**Comment by The0nix** [comment]
Nice! Thank you. I certainly love new naming and base classes. I will probably try to commit some transforms myself during the hacktoberfest. And the destinction should also be reflected in docs (readme) imo.
