### ISSUE TITLE
PyTorch audiomentations? 

### ISSUE THREAD

**Issue by mpariente** [iver56/audiomentations#44]
Hey

I haven't read all the code but this project looks great ! 

How would you feel about participating to a similar project in PyTorch? This would be great !

**Comment by iver56** [comment]
I have actually been thinking about this lately. Count me in. How should we proceed?

**Comment by mpariente** [comment]
Would you like to join Asteroid's slack to talk about this? 
Here is the [link](https://join.slack.com/t/asteroid-dev/shared_invite/zt-cn9y85t3-QNHXKD1Et7qoyzu1Ji5bcA)

**Comment by zh794390558** [comment]
Watch this.

**Comment by iver56** [comment]
I initiated the planning phase today:
https://github.com/asteroid-team/torch-audiomentations
