### ISSUE TITLE
Add Compose Transform 

### ISSUE THREAD

**Issue by zh794390558** [iver56/audiomentations#47]
A Compose transform can compose multi BaseTransform, may be used add multi same transform and other.

**Comment by iver56** [comment]
Can you give an example? How is this different from the existing `Compose`?

**Comment by zh794390558** [comment]
We can do two Transform controlled by one Prob.

**Comment by iver56** [comment]
We can make a callable that applies two transforms with a single probability like this:

`Compose([AddGaussianNoise(p=1.0), Normalize(p=1.0)], p=0.5)`

Does this cover your need, or would you like to elaborate?

**Comment by zh794390558** [comment]
But how `Compose([Compose([AddGaussianNoise(p=1.0), Normalize(p=1.0)], p=0.5), ...]` this work?

**Comment by iver56** [comment]
So you want to nest `Compose` instances, like this?

```
Compose(
    [
        Compose([AddGaussianNoise(p=1.0), Normalize(p=1.0)], p=0.5),
        Compose([AddBackgroundNoise(p=1.0, ...), Normalize(p=1.0)], p=0.5),
    ]
)
```

Can you tell me more about your underlying use case?

**Comment by zh794390558** [comment]
We can add AddShortNoise with some noises one time.

**Comment by iver56** [comment]
And how does that relate to shortcomings in `Compose`? I'll reopen this issue if it gets a proper description that I can understand.
