### ISSUE TITLE
support add random multi short noise with one wav 

### ISSUE THREAD

**Issue by zh794390558** [iver56/audiomentations#48]

**Comment by iver56** [comment]
Does `AddShortNoises` cover your use case? If not, could you please elaborate?

Here is an example of how you can use AddShortNoises:
https://github.com/iver56/audiomentations/blob/bd3cae38ddedad081463ecd785215bce2d3eb9c6/demo/demo.py#L167

**Comment by iver56** [comment]
Are you saying you want support for passing a file path (i.e. to a single wav file) instead of a folder path to `sounds_path`?

**Comment by zh794390558** [comment]
For now AddShortNoises only mix one noise file, we can mix N noise at one time.

**Comment by iver56** [comment]
`AddShortNoises` can add multiple different noises, with or without overlap, to a sound.

I'm trying to understand your use case. Can you elaborate? I'll reopen the issue if it gets a proper description
