### ISSUE TITLE
Add tanh distortion transform

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#50]

**Comment by pranav6670** [comment]
Can I work on this?

**Comment by iver56** [comment]
Yes please 👍

**Comment by pranav6670** [comment]
Hey @iver56, can you educate me on where to add my code and writing tests! Sorry, I am kinda noob here:(

**Comment by iver56** [comment]
You need to add a class `TanhDistortion` in https://github.com/iver56/audiomentations/blob/master/audiomentations/augmentations/transforms.py

You can look at other classes for inspiration

You also need to add a test file in this folder: https://github.com/iver56/audiomentations/tree/master/tests

You can look at the existing test files for inspiration

If you want to listen to the doings of your new augmentation transform, you can add it to the demo script and run it on your computer:

https://github.com/iver56/audiomentations/blob/master/demo/demo.py

**Comment by pranav6670** [comment]
Sure, thank you for the directions. I am planning to add tanh, atan and exponential distortions.

**Comment by iver56** [comment]
@pranav6670 How is it going?

**Comment by atamazian** [comment]
Can you specify desired input arguments names?

**Comment by atamazian** [comment]
Added with https://github.com/iver56/audiomentations/pull/107, please close this issue.
