### ISSUE TITLE
AddBackgroundNoise has no effect at all

### ISSUE THREAD

**Issue by scasasso** [iver56/audiomentations#54]
I am trying to use `AddBackgroundNoise` without success. The result after applying the transform is identical to the original clean file.

This my code:

```python
from audiomentations import Compose, AddBackgroundNoise
import librosa

# Define transforms
augmenter = Compose([
    AddBackgroundNoise(sounds_path='/path/to/noise/wav', p=1.)
])

# Load original (clean) audio
y, sr = librosa.load(/path/to/clean/file.wav,
                                sr=32000,
                                res_type="kaiser_fast",
                                mono=True)

# Apply augmentations
y_aug = augmenter(samples=y, sample_rate=sr)
```

The resulting `y_aug` is identical to the original `y`.

Any help is appreciated!
Thanks

**Comment by iver56** [comment]
Some things to check:


1) sounds_path should refer to a folder, not a file

2) If the clean file is all silence, then the output will also be all silence, since the level of the added noise is relative to the amount of signal

If this does not help, can you please share the audio files to help reproduce the issue?

**Comment by iver56** [comment]
@scasasso Are you still having this issue? Did you do more digging based on my comment above?

**Comment by iver56** [comment]
I added a note to the AddBackgroundNoise docstring. Closing this issue now due to lack of response. Let's reopen this if it's a bug that can be reproduced and should be fixed.

**Comment by laoyin** [comment]
> reproduce

[BAC009S0002W0122.wav.zip](https://github.com/iver56/audiomentations/files/6954912/BAC009S0002W0122.wav.zip)




`import numpy as np
import time
import os
from scipy.io import wavfile
from audiomentations import (
    AddGaussianNoise,
    TimeStretch,
    PitchShift,
    Shift,
    Normalize,
    FrequencyMask,
    TimeMask,
    AddGaussianSNR,
    Resample,
    ClippingDistortion,
    AddBackgroundNoise,
    AddShortNoises,
    PolarityInversion,
    Gain,
    Mp3Compression,
    LoudnessNormalization,
    Trim,
    LowPassFilter,
    HighPassFilter,
    BandPassFilter,
    ApplyImpulseResponse,
    Reverse,
)
from audiomentations.core.audio_loading_utils import load_sound_file
from audiomentations.core.transforms_interface import (
    MultichannelAudioNotSupportedException,
)
import librosa

noise_path = '/home/yinxingpan/audio_mentation/bg_noises'

augment = AddBackgroundNoise(
    sounds_path=noise_path,
    p=1
)



def read_raw_audio(audio, sample_rate=16000):
    wave, _ = librosa.load(os.path.expanduser(audio), sr=sample_rate)
    return wave


my_audio = read_raw_audio("abc.wav")

my_audio_with_noise = augment(my_audio, 16000)

wavfile.write("abc1.wav", rate=16000, data=my_audio_with_noise)
`

**Comment by laoyin** [comment]
> Some things to check:
> 
> 1. sounds_path should refer to a folder, not a file
> 2. If the clean file is all silence, then the output will also be all silence, since the level of the added noise is relative to the amount of signal
> 
> If this does not help, can you please share the audio files to help reproduce the issue?

[BAC009S0002W0122.wav.zip](https://github.com/iver56/audiomentations/files/6954945/BAC009S0002W0122.wav.zip)

@iver56 

```
import numpy as np
import time
import os
from scipy.io import wavfile
from audiomentations import (
    AddGaussianNoise,
    TimeStretch,
    PitchShift,
    Shift,
    Normalize,
    FrequencyMask,
    TimeMask,
    AddGaussianSNR,
    Resample,
    ClippingDistortion,
    AddBackgroundNoise,
    AddShortNoises,
    PolarityInversion,
    Gain,
    Mp3Compression,
    LoudnessNormalization,
    Trim,
    LowPassFilter,
    HighPassFilter,
    BandPassFilter,
    ApplyImpulseResponse,
    Reverse,
)
from audiomentations.core.audio_loading_utils import load_sound_file
from audiomentations.core.transforms_interface import (
    MultichannelAudioNotSupportedException,
)
import librosa

noise_path = '/home/yinxingpan/audio_mentation/bg_noises'

augment = AddBackgroundNoise(
    sounds_path=noise_path,
    p=1
)



def read_raw_audio(audio, sample_rate=16000):
    wave, _ = librosa.load(os.path.expanduser(audio), sr=sample_rate)
    return wave


my_audio = read_raw_audio("abc.wav")

my_audio_with_noise = augment(my_audio, 16000)

wavfile.write("abc1.wav", rate=16000, data=my_audio_with_noise)

```

**Comment by iver56** [comment]
@laoyin are you having this issue with AddBackgroundNoise as well? I see you added a speech recording and some code. Can you give me a bit more context?
