### ISSUE TITLE
Add support for multichannel audio data

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#55]
`shape=(num_samples, num_channels)` should be supported as well as `shape=(num_samples,)`

**Comment by francislata** [comment]
When is the expected delivery for this one @iver56?

**Comment by iver56** [comment]
Hi Francis, and thanks for your interest in this. I have no clear plan for this. I guess it's whenever I have time. If you want to speed this up, contributions are welcome!

By the way, yesterday I figured that shape=(num_channels, num_samples) is also sometimes something people use for multichannel audio. Should we support both?

**Comment by iver56** [comment]
Librosa (see https://github.com/librosa/librosa/issues/1130) will use the convention (num_channels, num_samples). I think I prefer this.

The other dimension ordering, (num_samples, num_channels), is used when loading and saving multichannel wav, where stereo samples are interleaved.

**Comment by francislata** [comment]
@iver56 - I think sticking to one specific ordering like `num_channels, num_samples` just like in `librosa` would be much better.

**Comment by iver56** [comment]
Agreed.

I have started some basic work on multichannel audio support here: https://github.com/iver56/audiomentations/commit/59707fd8f501ca7ee13ce1a8a3988a935ed26930

Contributions are welcome
