### ISSUE TITLE
Rename AddImpulseResponse to ApplyImpulseResponse?

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#56]
Any thoughts on this?

Should be done in a backwards-compatible manner of course.

**Comment by atamazian** [comment]
I think it should be renamed. In `torch-audiomentations` it's called `ApplyImpulseResponse`.

**Comment by iver56** [comment]
Agreed. I imagine that we could make an extra class `ApplyImpulseResponse` like

```
class ApplyImpulseResponse(AddImpulseResponse):
    pass
```

Then we could implement a deprecation warning for people using `AddImpulseResponse`, asking them to change their code to `ApplyImpulseResponse`

**Comment by iver56** [comment]
@atamazian Would you like to make a PR?

**Comment by atamazian** [comment]
OK. Can you assign this issue to me? I'll implement this.

**Comment by iver56** [comment]
Thanks :) Assigned to you now
