### ISSUE TITLE
Add high pass filter transformation

### ISSUE THREAD

**Issue by iver56** [iver56/audiomentations#7]

**Comment by iver56** [comment]
https://github.com/jiaaro/pydub/blob/master/pydub/effects.py#L251

**Comment by iver56** [comment]
https://pyaudiodsptools.readthedocs.io/en/latest/

**Comment by iver56** [comment]
https://github.com/asteroid-team/torch-audiomentations#highpassfilter

**Comment by atamazian** [comment]
Please assign me to this issue.

**Comment by atamazian** [comment]
This issue is solved, please close it.
