### ISSUE TITLE
Add `randomize_parameters()` in composition

### ISSUE THREAD

**Issue by SolomidHero** [iver56/audiomentations#71]
Hi!
I guess it would be nice to use freezing of parameters before all transformation right after generating them.
```python
augment = Compose([...])

...

# in any training loop

waves_to_equal_augment = [...]
sr = ...

augment.randomize_parameters(waves_to_equal_augment[0], sr)
augment.freeze_parameters() # it can be even used once!
for wav in waves_to_equal_augment:
  aug_wav = augment(wav)
  ...

augment.unfreeze_parameters() # it can be even dropped!
```

Currently parameters even can't be generated without `apply` of composition.

**Comment by iver56** [comment]
Sounds like a good addition. I would be happy to review and accept a PR that adds this
