### ISSUE TITLE
How to apply to stereo?

### ISSUE THREAD

**Issue by ZFTurbo** [iver56/audiomentations#73]
Currently audiomentations doesn't work with stereo audio.  Most of transformations failed with:

`librosa.util.exceptions.ParameterError: Invalid shape for monophonic audio: ndim=2, shape=(240000, 2)`

One of possible workaround is to apply same transormations for each channel independently. But how to use the same transformations with same parameters?

**Comment by ZFTurbo** [comment]
I tried code below but all files are the same in this case.

```
from a00_common_functions import *
from audiomentations import *
from scipy.io import wavfile

def get_augmentation():
    return Compose([
        AddGaussianNoise(min_amplitude=0.025, max_amplitude=0.026, p=1.0),
        TimeStretch(min_rate=1.7, max_rate=1.71, p=1.0),
        PitchShift(min_semitones=4, max_semitones=4, p=1.0),
        Shift(min_fraction=-0.2, max_fraction=0.2, rollover=True, p=1.0),
        FrequencyMask(min_frequency_band=0.0, max_frequency_band=0.5, p=1.0),
        TimeMask(min_band_part=0.0, max_band_part=0.1, fade=True, p=1.0),
        AddGaussianSNR(min_SNR=1.0, max_SNR=1.0, p=1.0),
        ClippingDistortion(min_percentile_threshold=0, max_percentile_threshold=20, p=1.0),
        Normalize(p=1.0),
    ], p=1.0)


def check_audiomentations():
    _, d = wavfile.read(INPUT_PATH + 'stereo.wav')
    print(d.shape, d.min(), d.max())
    wavfile.write('checker_orig.wav', sr, d)
    aug = get_augmentation()
    for i in range(10):
        aug.freeze_parameters()
        full_samples = []
        for j in range(d.shape[1]):
            samples = aug(samples=d[:, j], sample_rate=sr)
            full_samples.append(samples)
        full_samples = np.stack(full_samples, axis=-1)
        aug.unfreeze_parameters()
        wavfile.write('checker_{}.wav'.format(i), sr, full_samples)
        print(full_samples.shape, full_samples.min(), full_samples.max())

if __name__ == '__main__':
    check_audiomentations()

```

**Comment by ZFTurbo** [comment]
Ok, looks like found workaround for this:

```
def check_audiomentations():
    sr, d = wavfile.read(INPUT_PATH + 'stereo.wav')
    print(d.shape, d.min(), d.max())
    wavfile.write('checker_orig.wav', sr, d)
    aug = get_augmentation()
    for i in range(10):
        random.seed(int(time.time()))
        full_samples = []
        samples = aug(samples=d[:, 0], sample_rate=sr)
        full_samples.append(samples)
        aug.freeze_parameters()
        for j in range(1, d.shape[1]):
            samples = aug(samples=d[:, j], sample_rate=sr)
            full_samples.append(samples)
        full_samples = np.stack(full_samples, axis=-1)
        aug.unfreeze_parameters()
        wavfile.write(CACHE_PATH + 'checker_{}.wav'.format(i), sr, full_samples)
        print(full_samples.shape, full_samples.min(), full_samples.max())
```

**Comment by iver56** [comment]
Hi :)

Some transforms (currently `Normalize`, `Gain` and `PolarityInversion`) support stereo/multichannel with shape like `(channels, samples)`. Note that this dimension ordering differs from the way stereo audio is stored in wav files! Use numpy's transpose function to swap the axes.

If you want to add multichannel support to more transforms, that would be a welcome contribution. I would be happy to review and accept such pull requests.

You can indeed apply the same augmentation to two audio channels with `freeze_parameters()` and `unfreeze_parameters()`, as you have already discovered.

**Comment by iver56** [comment]
I added multichannel support in `Shift` just now: 3c406e00

**Comment by iver56** [comment]
`AddGaussianSNR` and `AddGaussianNoise` also support multichannel audio now: 0890fa39

**Comment by ZFTurbo** [comment]
May be it's good idea to create table in README.md with all avialable augmentations and some marks like stereo support. Also you can move there info about version when it was added.

**Comment by iver56** [comment]
`TimeMask` multichannel audio support: dc2285b2

**Comment by iver56** [comment]
Just picking some low-hanging fruits here 😄 🍒 🥝 🍌 🍓 🍏

**Comment by iver56** [comment]
`FrequencyMask` supports multichannel audio now: 5f370c2c

**Comment by iver56** [comment]
`ClippingDistortion` supports multichannel audio now: e436816c

**Comment by iver56** [comment]
`PitchShift` supports multichannel audio now: 1067d36c

However, the implementation is not "perfect". Waiting for https://github.com/librosa/librosa/issues/1085

**Comment by iver56** [comment]
> 
> 
> May be it's good idea to create table in README.md with all avialable augmentations and some marks like stereo support. Also you can move there info about version when it was added. Tail of version history can be moved to separate document I guess.

I added a table to README now:
https://github.com/iver56/audiomentations#multichannel-audio
