### ISSUE TITLE
Add an option for 'leaving the audio length unchanged' after applying impulse response 

### ISSUE THREAD

**Issue by ahikaml** [iver56/audiomentations#74]
Hi
Thank you for this library 
In my environment I call the "convolve" (in AddImpulseResponse\apply) with argument 'same' but I'm not sure that this is the best way to do that.
Thanks

**Comment by iver56** [comment]
You can slice off the extra sample at the end. Here's an example from torch-audiomentations (it uses pytorch, but the concept is similar in numpy):
https://github.com/asteroid-team/torch-audiomentations/blob/master/torch_audiomentations/augmentations/impulse_response.py#L83

If you want to add an option `leave_length_unchanged` to audiomentations, that would be a welcome pull request

**Comment by ahikaml** [comment]
Thank you for the quick response 👍

**Comment by iver56** [comment]
Added this feature in https://github.com/iver56/audiomentations/pull/77

**Comment by iver56** [comment]
The fix #77 is now available in version 0.15.0 on PyPI
