### ISSUE TITLE
Picking error when using the IR augmentation

### ISSUE THREAD

**Issue by ahikaml** [iver56/audiomentations#75]
I got the following error when I try to run the IR augmentation:
    **ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x00000228E9A0E228>: attribute lookup AddImpulseResponse.__load_ir on audiomentations.augmentations.transforms failed**

The error is gone when I remove the __load_ir  declaration in the init function (but then in the othere hand I lose the ability to read from the cache):
**self.__load_ir = functools.lru_cache(maxsize=lru_cache_size)(AddImpulseResponse.__load_ir)**

I'm using python 3.7 in windows. 
The error is triggered by multiprocessing\reduction.py module which called by pytorch.

From googling this issue it seems that it's related somehow to the level of a pickled function. 
https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function\
https://www.programmersought.com/article/12495762637/
 
From a short briefing on all issues in this repository it seems that nobody has encountered this error. 
Any idea how to solve it (or at least workaround it)?

Thanks

**Comment by iver56** [comment]
Yeah, sorry, multiprocessing isn't officially supported yet (see https://github.com/iver56/audiomentations#known-limitations)

You could try `v0.12.1` (instead of `v0.14.0`), where this exact error probably won't occur

If you want to help implement support for multiprocessing, that's a welcome contribution

**Comment by iver56** [comment]
Since you're using pytorch, you might want to consider using torch-audiomentations for applying impulse responses.

https://github.com/asteroid-team/torch-audiomentations

As you can see on the graph in readme, it's a lot faster as well

**Comment by ahikaml** [comment]
torch-audiomentations looks very nice indeed... 
I see that in this repository you used librosa for the Time Stretch and Pitch Shifting.
If I want to add the same functionality to torch-audiomentations repository, do you recommend to use torchaudio for that? Or any other library?

**Comment by iver56** [comment]
Yes. Use librosa or torchaudio.

**Comment by iver56** [comment]
The fix #76 is now available in version 0.15.0 on PyPI
