### ISSUE TITLE
AddGuassianNoise stops working(sometimes noise is generated, sometimes it is not)

### ISSUE THREAD

**Issue by ismailkhan007** [iver56/audiomentations#84]
I have been trying to add guassian noise into wav file. The issue is that one time the noise is added, and next time noise it not added. For example, i have been using below mentioned code:
![image](https://user-images.githubusercontent.com/65068274/104402191-912c4980-5577-11eb-877c-e323b693d8c2.png)

First time i run the code, noise is generated. next time i run the same code, noise is not generated. in short, sometimes noise is generated, other time, it is not.

Kindly help me understand the problem and possible solution. Thank you
I am using the module for my Final Year University Project.

I am using Spyder IDE.

Wavfile detail:
 Channels: stereo
sample rate: 48000
 Bits per sample: 16

**Comment by iver56** [comment]
Did you try p=1.0 instead of p=0.6?

**Comment by ismailkhan007** [comment]
> Did you try p=1.0 instead of p=0.6?

for p=1, it seems to be working. I have run same code 12 times  with p=1, and it worked. And it worked for other audio files as well, as long as p=1.
 But i also tried p with min and max value as well along with p\other p values. but one time it works, next time it does not. and this repeats.

**Comment by iver56** [comment]
p controls the probability of the transform being applied. What you are seeing is the intended behavior.
