### ISSUE TITLE
SNR inverse chracteristics

### ISSUE THREAD

**Issue by darkcurrent** [iver56/audiomentations#86]
Signal-to-noise ratio (SNR) is defined as the ratio of the power of a signal (meaningful input) to the power of background noise.

But the "AddGaussianSNR" method has arguments which have inverse chracteristics. When you increase SNR in the method the real SNR decreases. Should be the opposite.

**Comment by iver56** [comment]
I agree. This is confusing behavior and we should change it. We should also use dB

**Comment by iver56** [comment]
0921b406

**Comment by atamazian** [comment]
Suggested to fix with https://github.com/iver56/audiomentations/pull/108

**Comment by atamazian** [comment]
Fixed with https://github.com/iver56/audiomentations/pull/108, please close.
