### ISSUE TITLE
AddBackgroundNoise MultichannelAudioNotSupportedException

### ISSUE THREAD

**Issue by darkcurrent** [iver56/audiomentations#87]
When I use AddBackgroundNoise method, most of the time I got following error:
`MultichannelAudioNotSupportedException: AddBackgroundNoise only supports mono audio, not multichannel audio`
But the noise folder which I have pointed has _**16kHz, 16bit PCM(little/signed), 1 channel**_ wav files in it.

**Comment by iver56** [comment]
1) Can you please check the shape of the audio ndarray you are giving it? If it is not 1-dimensional, you may get that exception
2) If you want to help add support for multichannel audio, a contribution would be a welcome

**Comment by iver56** [comment]
58efb411

**Comment by darkcurrent** [comment]
Hello,
1. The background noise folder has wav files which are 16kHz, 16bit PCM(little/signed), 1 channel.
    And I gave to the augment method a numpy array which is shaped as (1, 8000).
    Both source and destinations files are in 500ms length.
2. Thank you for the invitation, I'll check if I can do anything. :)

**Comment by darkcurrent** [comment]
Sorry my mistake. 
I was confused because some of other methods accepts (1,N) shape but AddBackgroundNoise only accepts (N,) shape ...

**Comment by iver56** [comment]
I see. Yes, the problem was related to the shape. You can see a shape compatibility table here:

https://github.com/iver56/audiomentations#multichannel-audio

**Comment by iver56** [comment]
https://github.com/iver56/audiomentations/commit/24c438ea012ffefdb74d39ac7d62d8d9b276f9f9

**Comment by darkcurrent** [comment]
> I see. Yes, the problem was related to the shape. You can see a shape compatibility table here:
> 
> https://github.com/iver56/audiomentations#multichannel-audio

Thank you...
