### ISSUE TITLE
Random interruption pulses to augment ECG lead-off condition

### ISSUE THREAD

**Issue by darkcurrent** [iver56/audiomentations#88]
Hello,

I just wrote a function, for ECG augmentation. The main purpose is simulate the signals when the ECG electrodes are in lead-off condition. It can also be used for audio data augmentation.
The function generates random number of flat pulses with some noise on it. The pulses' amplitudes are between signal max-min range and pulses have random width. 
Maybe the function can be added here.

Regards,

```python
import wavio
import numpy as np
from matplotlib import pyplot as plt

audio_seg=wavio.read("sample_audio.wav").data.astype(np.float32).T[0]

def InterruptSignal(audio_seg, max_num_interruptions, noise_level, p):
    # audio_seg:             Audio segment (1D Numpy array)
    # max_num_interruptions: Maximum number of interruption pulses. Pulses are generated randomly
    # noise_level:           The level of noise to be added the pulses. "CNN's don't like constant values :)"
    # p:                     Triggering probability
    if np.random.random() < p / 1.:
        max_peak = np.max(audio_seg).astype(int)
        min_peak = np.min(audio_seg).astype(int)
        len_audio                = audio_seg.shape[-1]
        num_random_interruptions = np.random.randint(max_num_interruptions)+1
        interruption_start_times = (len_audio * np.random.random(num_random_interruptions)*4/5).astype(int)
        for interruption in interruption_start_times:
            interruption_len = int(len_audio*np.random.random()//5)
            interruption_val = np.random.randint(min_peak, max_peak)
            audio_seg[interruption:interruption+interruption_len] = interruption_val+np.random.normal(0, 1, interruption_len)*noise_level
    return audio_seg

fig, (ax1, ax2) = plt.subplots(2)
fig.suptitle('Two random interruptions with some noise')
ax1.plot(audio_seg[:5000])
ax2.plot(InterruptSignal(audio_seg[:5000],
                         max_num_interruptions=3,
                         noise_level=100,
                         p=1))
plt.show()
```
<img width="294" alt="interruptions" src="https://user-images.githubusercontent.com/6089944/108605641-75159680-73c6-11eb-950f-ffa38f1d93fb.PNG">

**Comment by iver56** [comment]
Interesting 👍 It can be added. Or maybe it can be an option in AddShortNoises?

**Comment by darkcurrent** [comment]
Hmm they looks so similar...
I think the only difference is the DC offset. So making an option to AddShortNoises makes more sense.

**Comment by atamazian** [comment]
Please assign this issue to me.

**Comment by iver56** [comment]
Thinking of it, maybe a separate class is better than adding yet another option to AddShortNoises? Because AddShortNoises has so many options already 😅

It could be a subclass of AddShortNoises that generates random interruption pulses on the fly instead of loading files from disk

**Comment by atamazian** [comment]
OK

**Comment by atamazian** [comment]
I suggest to close this issue since it's replaced by https://github.com/iver56/audiomentations/issues/160

**Comment by iver56** [comment]
Yes. Once #160 is closed, I'll see if I can provide a quick example of how InterruptPulse can be done with it

**Comment by iver56** [comment]
InterruptPulse ingredients:

* bleeding edge audiomentations (or >=0.23.0 when it gets released)
* `AddShortNoises` with signal_gain_in_db_during_noise set to a very low value, like -100
* A personal script to generate the various white noises with DC offset (length, intensity and other things can be varied as you want. Export the sounds to wav files in a folder

like

```
transform = AddShortNoises(
    sounds_path="/path/to/lead-off-noises",
    min_snr_in_db=0,
    max_snr_in_db=8,
    noise_rms="relative",
    min_time_between_sounds=2.0,
    max_time_between_sounds=4.0,
    burst_probability=0.0,
    min_fade_in_time=0.001,
    max_fade_in_time=0.001,
    min_fade_out_time=0.001,
    max_fade_out_time=0.001,
    signal_gain_in_db_during_noise=-100.0,
    p=1.0,
)
```
