### ISSUE TITLE
Mp3Compression NoBackendError

### ISSUE THREAD

**Issue by darkcurrent** [iver56/audiomentations#89]
I am trying to use Mp3Compression with backend="pydub". But having  this NoBackendError below.
Do you have any idea about the issue?
Regards,
- Windows10
- python 3.8.5
- ffmpeg version = 4.3.1 (conda package)
- pydub version = 0.23.1 (conda package)

```
C:\Users\user\anaconda3\envs\ml\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\anaconda3\envs\ml\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    145     try:
--> 146         with sf.SoundFile(path) as sf_desc:
    147             sr_native = sf_desc.samplerate

~\anaconda3\envs\ml\lib\site-packages\soundfile.py in __init__(self, file, mode, samplerate, channels, subtype, endian, format, closefd)
    628                                          format, subtype, endian)
--> 629         self._file = self._open(file, mode_int, closefd)
    630         if set(mode).issuperset('r+') and self.seekable():

~\anaconda3\envs\ml\lib\site-packages\soundfile.py in _open(self, file, mode_int, closefd)
   1182             raise TypeError("Invalid file: {0!r}".format(self.name))
-> 1183         _error_check(_snd.sf_error(file_ptr),
   1184                      "Error opening {0!r}: ".format(self.name))

~\anaconda3\envs\ml\lib\site-packages\soundfile.py in _error_check(err, prefix)
   1356         err_str = _snd.sf_error_number(err)
-> 1357         raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
   1358 

RuntimeError: Error opening 'C:\\Users\\user\\AppData\\Local\\Temp\\tmp_compressed_37ed35fe-9a1.mp3': Format not recognised.

During handling of the above exception, another exception occurred:

NoBackendError                            Traceback (most recent call last)
<ipython-input-296-889e15591d71> in <module>
     25 ])
     26 
---> 27 augmented_data = augment(samples=data.T[0], sample_rate=SAMPLE_RATE)
     28 
     29 plt.plot(augmented_data)

~\anaconda3\envs\ml\lib\site-packages\audiomentations\core\composition.py in __call__(self, samples, sample_rate)
     50                 random.shuffle(transforms)
     51             for transform in transforms:
---> 52                 samples = transform(samples, sample_rate)
     53 
     54         return samples

~\anaconda3\envs\ml\lib\site-packages\audiomentations\core\transforms_interface.py in __call__(self, samples, sample_rate)
     74                     )
     75                 )
---> 76             return self.apply(samples, sample_rate)
     77         return samples
     78 

~\anaconda3\envs\ml\lib\site-packages\audiomentations\augmentations\transforms.py in apply(self, samples, sample_rate)
   1054             return self.apply_lameenc(samples, sample_rate)
   1055         elif self.backend == "pydub":
-> 1056             return self.apply_pydub(samples, sample_rate)
   1057         else:
   1058             raise Exception("Backend {} not recognized".format(self.backend))

~\anaconda3\envs\ml\lib\site-packages\audiomentations\augmentations\transforms.py in apply_pydub(self, samples, sample_rate)
   1134         file_handle.close()
   1135 
-> 1136         degraded_samples, _ = librosa.load(tmp_file_path, sample_rate)
   1137 
   1138         os.unlink(tmp_file_path)

~\anaconda3\envs\ml\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    161         if isinstance(path, (str, pathlib.PurePath)):
    162             warnings.warn("PySoundFile failed. Trying audioread instead.")
--> 163             y, sr_native = __audioread_load(path, offset, duration, dtype)
    164         else:
    165             raise (exc)

~\anaconda3\envs\ml\lib\site-packages\librosa\core\audio.py in __audioread_load(path, offset, duration, dtype)
    185 
    186     y = []
--> 187     with audioread.audio_open(path) as input_file:
    188         sr_native = input_file.samplerate
    189         n_channels = input_file.channels

~\anaconda3\envs\ml\lib\site-packages\audioread\__init__.py in audio_open(path, backends)
    114 
    115     # All backends failed!
--> 116     raise NoBackendError()

NoBackendError: 
```

**Comment by iver56** [comment]
This looks like an issue with librosa/audioread/ffmpeg. Is ffmpeg correctly installed?

Have you tried the other backend, `lameenc`?

`Mp3Compression(backend="lameenc")`

**Comment by iver56** [comment]
Have you got PySoundFile installed?

If you can make a small script that loads an mp3 file with librosa, that's a simpler way of debugging for you

**Comment by darkcurrent** [comment]
I have got ffmpeg installed as a conda package. (v4.3.1)
PySoundFile is also installed. (v0.9.0)
When I load a mp3 file with librosa everything is normal...

```python
import librosa
librosa.load('100 Suns.mp3')
```
`Output: (array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 22050)`

Any idea?

**Comment by iver56** [comment]
Can you try to check what the content of the tmp mp3 is? And have you tried to switch backend to lameenc?

**Comment by darkcurrent** [comment]
You are correct! The temp mp3 file is not a valid file. It is only 261bytes and librosa gave the same error when I try to load the mp3 file. "Format not recognised."

I tried with lameenc.  Lame encoder gave same warning at the and but did not output any errors. 
`C:\Users\user\anaconda3\envs\ml\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")`
After augmentation with lame I plotted the input and output. Output is like a random noise between -1 and 1.

Maybe it could be only my fault? Here is the usage:

```python
SAMPLE_RATE    = 16000
data           = wavio.read("mic_F03_si1011.wav").data.astype(np.float32)
augment        = Compose([Mp3Compression(p=1.0, min_bitrate=128, max_bitrate=256, backend="lameenc")])
augmented_data = augment(samples=data.T[0], sample_rate=SAMPLE_RATE)

# Plot and listen
fig, (ax1, ax2) = plt.subplots(2)
fig.suptitle('Input and Output')
ax1.plot(data)
ax2.plot(augmented_data)
plt.show()
sd.play(augmented_data.T.astype(np.short), SAMPLE_RATE)
```
<img width="318" alt="input-output" src="https://user-images.githubusercontent.com/6089944/108625172-6bd60980-745a-11eb-895c-15d8d569eb2f.PNG">

**Comment by iver56** [comment]
I suspect that `wavio.read("mic_F03_si1011.wav").data.astype(np.float32)` will give you a numpy array with very large numbers instead of being within the range [-1, 1]. This is probably the reason why you're seeing garbled audio data out

**Comment by iver56** [comment]
Can you try to scale your data to be within the range [-1, 1] and try again? See also https://github.com/iver56/audiomentations#known-limitations

**Comment by darkcurrent** [comment]
Thank you Iver, that's my bad. After scaling, lameenc option works normally now. 
```python
from sklearn.preprocessing import minmax_scale
data = minmax_scale(data, feature_range=(-1,1))
```
The beggining and ending of the signal is little bit longer as expected but it can be trimmed easily. 

<img width="299" alt="input-output" src="https://user-images.githubusercontent.com/6089944/108625863-33d0c580-745e-11eb-8ffc-7ffa5a9d6484.PNG">

By the way the problem with the Pydub backend still persists. Solving the lameenc problem is enough for me, but if there is anything you want to try with pydub  backend in my computer in terms of contributing to the audiomentations project, I can help.

**Comment by darkcurrent** [comment]
1. I have reinstalled ffmpeg conda package (v4.3.1) several times but I had no luck with this.
2. After that I uninstalled ffmpeg package from local conda enviroment and installed ffmpeg binaries (v4.3.2) to disk manually. 
3. Then I write binaries path to the system enviroment variables. 

Now pydub backend is working properly! For some reason pydub->librosa doesn't reach ffmpeg from local conda enviroment. _(at least for my situation)_
I hope that information would be useful for someone...

And thank you for your time Iver...

**Comment by iver56** [comment]
> The beggining and ending of the signal is little bit longer as expected but it can be trimmed easily.

Right. The lameenc variant does indeed introduce a bit of an offset in the beginning, which is annoying. As far as I know, the pydub one does not have that issue.

I'm glad you were able to figure it out
