### ISSUE TITLE
What is p in AdddImpulseResponse

### ISSUE THREAD

**Issue by shakeel608** [iver56/audiomentations#94]
What is p in AdddImpulseResponse

**Comment by iver56** [comment]
It controls the probability of the augmentation being applied to the given piece of audio. If you want it to always be applied, set it to 1.0

**Comment by iver56** [comment]
248c3946

**Comment by shakeel608** [comment]
@iver56  Thank you for your quick feedback
When I apply the AddImpulseResponse as a data augmentation, my original audio utterance gets lost in the augmentation, how can we control how much to perturb the original signal ?

**Comment by iver56** [comment]
It depends on the impulse responses you use. If you want a result closer to the original, you can either tweak your impulse responses or make a mix of the input and the perturbed audio.

**Comment by shakeel608** [comment]
How to mix those two , I think you have not mentioned that in your docs

**Comment by shakeel608** [comment]
Thank you for the direction,
I am done with the mixing,
You can close the issue now

**Comment by iver56** [comment]
How to mix two pieces of audio together? With addition. Assuming you have two numpy arrays `original_audio` and `perturbed_audio`, here's how you can do that:

```
import math

mix_level = 0.3  # between 0 and 1
my_mix = math.sqrt(mix_level) * perturbed_audio + math.sqrt(mix_level - 1) * original_audio
```

**Comment by iver56** [comment]
https://github.com/iver56/audiomentations/issues/96
